# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '17.0'

# ✅ react-native-maps에서 Google Maps를 사용하겠다고 명시
ENV['RCT_MAPS_IOS_USE_GOOGLE_MAPS'] = '1'

prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'localmarketfinder' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => true,
    :new_arch_enabled => false,
  )

  # ✅ Google Maps
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'GoogleMaps', '7.4.0'
  pod 'react-native-maps', :path => rn_maps_path
  pod 'react-native-google-maps', :path => rn_maps_path

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

  end
end
